[package]
name = "egli"
version = "0.1.0"
authors = ["Nerijus Arlauskas <nercury@gmail.com>"]
license = "MIT OR Apache-2.0"

[dev-dependencies.x11]
features = ["xlib"]
version = "2.3"

[dependencies]
libc = "0.2"
bitflags = "0.5"

[features]
"egl-1.5" = []
